#
# Copyright (C) [2020] Futurewei Technologies, Inc.
#
# FORCE-RISCV is licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR
# FIT FOR A PARTICULAR PURPOSE.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ALL_SRCS := Register_test_top.cc Register_functional_tests.cc Register_unit_tests.cc Log.cc Register.cc UtilityFunctions.cc Random.cc Config.cc XmlTreeWalker.cc \
  	    pugixml.cc Architectures.cc Enums.cc ObjectRegistry.cc ChoicesModerator.cc GenException.cc Choices.cc ChoicesFilter.cc Constraint.cc ConstraintUtils.cc RegisterRISCV.cc ChoicesParser.cc RegisterInitPolicy.cc GenCondition.cc RegisterReserver.cc RegisterReserverRISCV.cc ReservationConstraint.cc EnumsRISCV.cc StringUtils.cc PathUtils.cc
TARGET_NAME := Register_test
