#
# Copyright (C) [2020] Futurewei Technologies, Inc.
#
# FORCE-RISCV is licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR
# FIT FOR A PARTICULAR PURPOSE.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# add all necessary source files here
#ALL_SRCS := Constraint_test.cc Log.cc Constraint.cc ConstraintUtils.cc Random.cc GenException.cc Enums.cc UtilityFunctions.cc Constraint_test3.cc # for debugging
#ALL_SRCS := Constraint_test.cc Log.cc Constraint.cc ConstraintUtils.cc Random.cc GenException.cc Enums.cc UtilityFunctions.cc Constraint_test5.cc # for testing
ALL_SRCS := Constraint_test.cc Log.cc Constraint.cc ConstraintUtils.cc Random.cc GenException.cc Enums.cc UtilityFunctions.cc Constraint_test1.cc Constraint_test2.cc Constraint_test3.cc Constraint_test4.cc Constraint_test5.cc Constraint_test6.cc StringUtils.cc
TARGET_NAME := Constraint_test
