#
# Copyright (C) [2020] Futurewei Technologies, Inc.
#
# FORCE-RISCV is licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR
# FIT FOR A PARTICULAR PURPOSE.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# add all necessary source files here
ALL_SRCS := AddressSolutionStrategy_test.cc Log.cc AddressSolutionStrategy.cc AddressTagging.cc OperandSolution.cc OperandSolutionMap.cc Constraint.cc Random.cc GenException.cc ConstraintUtils.cc Enums.cc UtilityFunctions.cc Register.cc pugixml.cc ObjectRegistry.cc Config.cc Architectures.cc XmlTreeWalker.cc RegisterReserver.cc ChoicesModerator.cc Choices.cc ChoicesFilter.cc RegisterInitPolicy.cc ReservationConstraint.cc EnumsRISCV.cc StringUtils.cc PathUtils.cc
TARGET_NAME := AddressSolutionStrategy_test
